ALTER TYPE "SaleContractStage" ADD VALUE IF NOT EXISTS 'TASK_APPROVED_REVIEW_PENDING';
ALTER TYPE "SaleContractStage" ADD VALUE IF NOT EXISTS 'TASK_REJECTED_REVIEW_PENDING';

ALTER TABLE "sales"
  ADD COLUMN "taskIsBeingEdited" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "taskEditorName" TEXT,
  ADD COLUMN "taskEditorActivity" TEXT,
  ADD COLUMN "taskEditorLastSeenAt" TIMESTAMP(3),
  ADD COLUMN "taskLastMessage" TEXT;
